apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: up5ym9mbf-python
  janus-idp.io/tekton: up5ym9mbf-python
  backstage.io/kubernetes-id: up5ym9mbf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: up5ym9mbf-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
