apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: up5ym9mbf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: up5ym9mbf-python 
  name: up5ym9mbf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: up5ym9mbf-python 
